/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccomplishmentsRouteImport } from './routes/accomplishments'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsRouteImport } from './routes/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccomplishmentsRoute = AccomplishmentsRouteImport.update({
  id: '/accomplishments',
  path: '/accomplishments',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accomplishments': typeof AccomplishmentsRoute
  '/arcade': typeof ArcadeRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accomplishments': typeof AccomplishmentsRoute
  '/arcade': typeof ArcadeRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accomplishments': typeof AccomplishmentsRoute
  '/arcade': typeof ArcadeRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accomplishments' | '/arcade' | '/contact' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accomplishments' | '/arcade' | '/contact' | '/projects'
  id:
    '__root__' | '/' | '/accomplishments' | '/arcade' | '/contact' | '/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccomplishmentsRoute: typeof AccomplishmentsRoute
  ArcadeRoute: typeof ArcadeRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accomplishments': {
      id: '/accomplishments'
      path: '/accomplishments'
      fullPath: '/accomplishments'
      preLoaderRoute: typeof AccomplishmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccomplishmentsRoute: AccomplishmentsRoute,
  ArcadeRoute: ArcadeRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
